version: "3.9"

services:

  postgres:
    image: docker.io/postgres:10-alpine
    environment:
      POSTGRES_USER: beta_sd
      POSTGRES_PASSWORD: lag404
      POSTGRES_DATABASE: clima
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: unless-stopped
    volumes:
      - ./schemas:/var/lib/postgresql/data
  api:
    build: proyecto
    restart: unless-stopped
    volumes:
      - ./proyecto:/opt
      - ./config:/opt/config
    depends_on:
      - postgres
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." /opt/docker-run.sh
