database: postgresql://beta_sd:lag404@postgres/clima

# uvicorn arguments
allowed_args_for_uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: false

logging:
  version: 1
  formatters:
    normal:
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: normal
      filename: omni_api.log
      maxBytes: 10485760
      backupCount: 10
    console:
      class: logging.StreamHandler
      formatter: normal
  loggers:
    omni_api:
      level: DEBUG
      handlers: [file, console]
  root:
    level: DEBUG
    handlers: [file, console]